/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdc.part.pkg2;

/**
 *
 * @author Admin
 */
public class ReceiptFrame extends javax.swing.JFrame {

    /**
     * @return the displayPrice
     */
    public javax.swing.JLabel getDisplayPrice() {
        return displayPrice;
    }

    /**
     * @param displayPrice the displayPrice to set
     */
    public void setDisplayPrice(javax.swing.JLabel displayPrice) {
        this.displayPrice = displayPrice;
    }

    /**
     * @return the displaySeatBooked
     */
    public javax.swing.JLabel getDisplaySeatBooked() {
        return displaySeatBooked;
    }

    /**
     * @param displaySeatBooked the displaySeatBooked to set
     */
    public void setDisplaySeatBooked(javax.swing.JLabel displaySeatBooked) {
        this.displaySeatBooked = displaySeatBooked;
    }

    /**
     * @return the displayService
     */
    public javax.swing.JLabel getDisplayService() {
        return displayService;
    }

    /**
     * @param displayService the displayService to set
     */
    public void setDisplayService(javax.swing.JLabel displayService) {
        this.displayService = displayService;
    }

    /**
     * @return the displayTrainLine
     */
    public javax.swing.JLabel getDisplayTrainLine() {
        return displayTrainLine;
    }

    /**
     * @param displayTrainLine the displayTrainLine to set
     */
    public void setDisplayTrainLine(javax.swing.JLabel displayTrainLine) {
        this.displayTrainLine = displayTrainLine;
    }

    /**
     * Creates new form ReceiptFrame
     */
    public ReceiptFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        trainServiceLabel = new javax.swing.JLabel();
        trainLineLabel = new javax.swing.JLabel();
        seatBookedLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        displayService = new javax.swing.JLabel();
        displayTrainLine = new javax.swing.JLabel();
        displaySeatBooked = new javax.swing.JLabel();
        displayPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookSeats = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("========RECEIPT========");

        trainServiceLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        trainServiceLabel.setText("Train Service: ");

        trainLineLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        trainLineLabel.setText("Train Line");

        seatBookedLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        seatBookedLabel.setText("Seat Booked");

        priceLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        priceLabel.setText("Total Price");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("==================================================");

        displayService.setText("--");

        displayTrainLine.setText("--");

        displaySeatBooked.setText("--");

        displayPrice.setText("--");

        bookSeats.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(bookSeats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(priceLabel)
                        .addGap(21, 21, 21)
                        .addComponent(displayPrice))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trainServiceLabel)
                                    .addComponent(trainLineLabel))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(displayTrainLine)
                                    .addComponent(displayService)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seatBookedLabel)
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(displaySeatBooked, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel6)))
                .addContainerGap(508, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displaySeatBooked, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainServiceLabel)
                    .addComponent(displayService))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainLineLabel)
                    .addComponent(displayTrainLine))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seatBookedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(displayPrice))
                .addGap(181, 181, 181))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> bookSeats;
    private javax.swing.JLabel displayPrice;
    private javax.swing.JLabel displaySeatBooked;
    private javax.swing.JLabel displayService;
    private javax.swing.JLabel displayTrainLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel seatBookedLabel;
    private javax.swing.JLabel trainLineLabel;
    private javax.swing.JLabel trainServiceLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the bookSeats
     */
    public javax.swing.JList<String> getBookSeats() {
        return bookSeats;
    }

    /**
     * @param bookSeats the bookSeats to set
     */
    public void setBookSeats(javax.swing.JList<String> bookSeats) {
        this.bookSeats = bookSeats;
    }
}
